### ISSUE TITLE
Unpack Microsoft cab file

### ISSUE THREAD

**Issue by enzok** [jbremer/sflock#14]
I tried adding support for unpacking Microsoft cab files using 7z and Ace as templates. I'm using cabextract as the external binary. I'm getting the following error:

"Detected potential out-of-path arbitrary overwrite!"

Not sure if this is zip jail related or not. I can't reproduce that error running cabextract from the command line.

Here's the code:

```
import os
import subprocess
import tempfile

from sflock.abstracts import Unpacker

class CabFile(Unpacker):
    name = "cabfile"
    exe = "/usr/bin/cabextract"
    exts = ".cab"
    magic = "Microsoft Cabinet archive"

    def unpack(self, password=None, duplicates=None):
        dirpath = tempfile.mkdtemp()

        if self.f.filepath:
            filepath = os.path.abspath(self.f.filepath)
            temporary = False
        else:
            filepath = self.f.temp_path(".cab")
            temporary = True

        try:
            subprocess.check_call([
                self.zipjail, filepath, dirpath,
                self.exe, "-d {}".format(dirpath), filepath,
            ], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
        except subprocess.CalledProcessError as e:
            self.f.mode = "failed"
            self.f.error = e

        if temporary:
            os.unlink(filepath)

        return self.process_directory(dirpath, duplicates)
```

**Comment by jbremer** [comment]
Thanks @enzok, excellent choice regarding `.cab`, I think I forgot about that one :-)
Yes, that's a `zipjail`-related issue/feature, I'll check it out in a little bit!

**Comment by enzok** [comment]
I just noticed that I get the same error message with an ACE file where the content file ends in ..exe

**Comment by jbremer** [comment]
@enzok If you can share a sample for that I'd be very happy to see that!

**Comment by enzok** [comment]
what's the best private way to send it to you?

**Comment by enzok** [comment]
nevermind, lol, it's on VT, fa18cfd37413246b448546f7f9497de4

**Comment by jbremer** [comment]
Turns out that's not actually a `.cab` file, but rather an `.ace` one. As you can see in the two commits above I've fixed the issue here, which turned out to be related to having double dots in the filename, e.g., `a..exe`.
I've also pushed a new version of `sflock`, namely `0.2.8`, which you can upgrade to and your file will work just fine. Closing as resolved.
If you do find a `.cab` file I'll be happy to merge the module you shared earlier. And if you have any other questions or feedback, do let me know :-)

**Comment by enzok** [comment]
Thanks. I'll provide the .cab file, I misunderstood and thought you wanted
the .ace.

**Comment by jbremer** [comment]
Ah, yes, I see the confusion. More samples is always more better, though :-)

**Comment by enzok** [comment]
Here's a cab file to test.

[readelf.cab.zip](https://github.com/jbremer/sflock/files/967984/readelf.cab.zip)

**Comment by jbremer** [comment]
Oke, thanks. Out of curiosity, did you see any malicious `.cab` files in the wild, or are you simply interested in `sflock` also supporting `.cab` files?

**Comment by enzok** [comment]
yes, i do have one delivered via email attachment, let me see if I can share it.

**Comment by enzok** [comment]
VT hash: e1cf86476f65cd663c5c56cdd9114d88c145420ace3c983bc103be258c25eadc

**Comment by jbremer** [comment]
Sweet, thanks! I'll have a look later.

**Comment by jbremer** [comment]
@enzok Done! I'm going to have a look at support for `.lnk` files as well and will be pushing out a new version of `sflock` depending on my results there ;-)

**Comment by jbremer** [comment]
@enzok I've pushed version `0.2.9` including the `.cab` extraction module, hope it works as expected!
Closing this issue as resolved, as usual looking forward to more feedback or suggestions :-)

**Comment by enzok** [comment]
Awesome. Thanks.
