### ISSUE TITLE
Sflock does not recognize CDFV2 files

### ISSUE THREAD

**Issue by FernandoDoming** [jbremer/sflock#17]
<img width="915" alt="screen shot 2017-06-28 at 10 34 45" src="https://user-images.githubusercontent.com/6620286/27627831-6e796d78-5bed-11e7-8844-f469c32ac17b.png">

Package is not the appropriate (should be doc) and it is not selected by default.

**Comment by jbremer** [comment]
filetype would indicate a potentially corrupt file, can you share the hash?

**Comment by doomedraven** [comment]
shared in PM ;)
it not corrupted as i can parse it with `vt -peo x`

**Comment by FernandoDoming** [comment]
c26a351c36ac03aa09f5d98531a103f971b84e22b6a1312bf1dc501421434290

In this case it is a office document, but as @doomedraven pointed out it can also be an outlook message.

**Comment by jbremer** [comment]
I've fixed the `outlook.msg` & `outlook2.msg` support without extension as well as `doc` identification for the `c26a35..` file. Please verify with latest `sflock` version (in Git), will be pushing out a new release one of these days.

**Comment by jbremer** [comment]
Tested as working, closing. Thanks @FernandoDoming.
